### PR TITLE
Add predefined breakpoints that can be set outside of an active session

### PR DESCRIPTION
**Pull request by mallt**
This PR adds a variable to which a list of predefined breakpoints can be added that can be set outside of an active geben session, and will be set as session breakpoints during the geben-session-enter-hook.

When clearing all breakpoints with <kbd>U</kbd> the list of predefined breakpoints will be cleared as well.

geben-predefined-breakpoints

### CODE REVIEW

**Comment by ksjogo** [comment]
Looks great to me. 
I did not look deeper into the filename handling yet, is there any support in geben for mapping local-path to vagrant/remote-paths?

**Comment by mallt** [comment]
Thanks!
I haven't done any remote debugging yet with geben, but according this article it should be possible using an SSH tunnel: https://devblog.more-onion.com/debugging-remote-drupal-site-through-ssh-tunnel-emacs

**Comment by ksjogo** [comment]
Geben and connect_back is running fine over ip on the local network, the problem is that remote file paths won't match up, so if I would set breakpoints on file paths from my local machine they won't get breaked at. So I was wondering if there already is some kind of mapping/path substitution in place.

**Comment by ahungry** [comment]
Nice!  Going to merge this in and we can work on the remote issue as necessary (avoid using this feature or whatever).

**Comment by ahungry** [comment]
Maybe add a small note about the function in the README too

**Pull request merged**
