### PR TITLE
Add evaluation of current line

### PR DESCRIPTION
**Pull request by mallt**
This PR adds a function to evaluate the current line, which I often find useful while debugging.

### CODE REVIEW

**Comment by mallt** [comment]
Thanks!

**Comment by ahungry** [comment]
Since this is a top level bind, can the docstring be a little more clear?  What is being evaluated?  (in what context - a line of elisp, a line of DBGp, or a line of the code being debugged)?

Just so it is less ambiguous to someone reading the docstring for what sounds like a general eval function.

**Comment by mallt** [comment]
Ok no problem, I'll try to push a clearer doc string later on today. (it's a line of code being debugged)

**Comment by ahungry** [comment]
Thanks, great change though!

**Pull request merged**
